In [1]:
import numpy as np

In [2]:
#let's build up an array 
#from here and below i'll use semicolons only in order to not forget to use them in C++ code 

arr = np.array((1, 2, 3));
arr_ = np.array(((1, 1), (2, 2)));

print(arr);
print("\n");
print(arr_);

[1 2 3]


[[1 1]
 [2 2]]


In [3]:
#let's get the type of an array's elements 
print(arr.dtype); 
#other properties of array:
# shape -> 
print(arr.shape);
# nbytes -> 
print(arr.nbytes);

int64
(3,)
24


In [4]:
#let's fill arrays with some sort of data 

arr1 = np.arange(1, 10, 2); #from, to, step 
print(arr1);

arr2 = np.zeros(7); #num of elements 
print(arr2);

arr3 = np.ones(7); #num of elements 
print(arr3)

arr4 = np.linspace(0, 10, 10); #kind a great way to do an interpolation #from, to, num of elements 
print(arr4);

arr5 = np.logspace(0, 3, 5); #from, to, num of elements 
print(arr5);

[1 3 5 7 9]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [5]:
#operation via arrays (or operation with const and array)

arr1 = np.array((1, 1, 1));
arr2 = np.array((2, 2, 2));

#sum 
print(arr1 + arr2); #each a[i] + b[i] 
#substraction 
print(arr1 - arr2); #each a[i] - b[i] 
#multiplication 
print(arr1 * arr2); #each a[i] * b[i] 
#division
print(arr1 / arr2); #each a[i] / b[i] 

[3 3 3]
[-1 -1 -1]
[2 2 2]
[0.5 0.5 0.5]


In [6]:
#also it's possible to use function for each element of array

print(np.cos(arr1)); #each cos(a[i])
#other functions:
#sin
#log

#usage of true/false sentences 
print(arr1 > arr2);

[0.54030231 0.54030231 0.54030231]
[False False False]


In [7]:
#∀ 
print(np.all(arr1 > arr2));


#∃
print(np.any(arr1 > arr2));

False
False


In [8]:
#+- ∞
print(np.inf);

#pi/e
print(np.e);

inf
2.718281828459045


In [9]:
#cumsum
print(arr1.cumsum()); #a[i] = a[i-1] + a[i-2] + .... a[0]

#sort 
print(np.sort(arr1));

[1 2 3]
[1 1 1]


In [10]:
#union of arrays:
print(np.hstack((arr1, arr2)));

#separation of arrays:
print(np.hsplit(np.hstack((arr1, arr2)), 2));

#append, delete and insert aren't inplace functions (so they doesn't change original arrray (!))
print(np.insert(arr1, 3, 8));

[1 1 1 2 2 2]
[array([1, 1, 1]), array([2, 2, 2])]
[1 1 1 8]


In [11]:
#spliting arrays
print(arr[1:5:2]); #start:stop:step

#reversed array 
print(arr1[::-1]);

#These procedures do not create a new array, but only make a proper pointer. So if you change b = a[0:3], a will also be changed
#to make copy
b = arr1.copy();

[2]
[1 1 1]


In [12]:
#put array's elements into diagonal of new array
arr1 = np.diag(np.arange(1, 5));
print(arr1);

#create identity matrix
arr2 = np.eye(4);
print(arr2);

#trace computates sum of diagonal elements
print(np.trace(arr2));

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4.0


In [13]:
#matrix multiplication
print(arr1 @ arr2);

#matrix shape 
arr1 = np.arange(24);
arr2 = arr1.reshape(4, 6);
arr3 = arr2.reshape(4, 2, 3);

print("\n");
print(arr1);
print("\n");
print(arr2);
print(arr3);

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [14]:
#Tensors 
Ten = np.arange(64).reshape(8, 2, 4);
print(Ten);

#Summation of Tensor's values 
print(Ten.shape);
print(np.sum(Ten, axis = 0), "\n"); #it leave 2*4 matrix

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]
(8, 2, 4)
[[224 232 240 248]
 [256 264 272 280]] 



In [29]:
#Elements of linear algebra
Ten_2 = np.array(((2,1), (2, 3)));
#Determinant
print(np.linalg.det(Ten_2));

#Inv
print(np.linalg.inv(Ten_2));

#Transporation 
print(Ten_2.T);

4.0
[[ 0.75 -0.25]
 [-0.5   0.5 ]]
[[2 2]
 [1 3]]


### Solving system of linear equations
$$
    A \cdot x=\nu
$$

In [17]:
a = np.array(((2,1), (2, 3)));
v = np.array((5, -10));
print(np.linalg.solve(a, v));

[ 6.25 -7.5 ]


### Searching the eigenvectors and eigenvalues
$$
A \cdot x = \lambda \cdot x
$$

In [30]:
values, (vector1, vector2) = np.linalg.eig(a);
print(values);
print(vector1);
print(vector2);

[1. 4.]
[-0.70710678 -0.4472136 ]
[ 0.70710678 -0.89442719]
